package limit;

import control.ControleVendas;
import model.*;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class LimitePagamento extends javax.swing.JFrame {

    //Declaração das variáveis
    private ControleVendas ctrVenda;
    private Vector<Corretor> vec;

    //Metodo construtor
    public LimitePagamento(ControleVendas pCtrVendas) {
        //Recebe o controle de vendas
        ctrVenda = pCtrVendas;
        //Recebe a lista de vendedores
        vec = new Vector();
        initComponents();
        //Desabilita a possibilidade de edição dos campos de ganho no ano e no mes
        jTextFieldGanhoAno.setEditable(false);
        jTextFieldGanhoMes.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCorretor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonPagar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGanhoMes = new javax.swing.JTextField();
        jTextFieldGanhoAno = new javax.swing.JTextField();
        jTextFieldData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/icons/jframeicon.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel1.setText("Data desejada: ");

        String[] str = new String[vec.size()];
        int cont = 0;
        for(Corretor ct: vec){
            str[cont] = ct.getNome();
            cont++;
        }
        jComboBoxCorretor.setModel(new javax.swing.DefaultComboBoxModel<>(str));

        jLabel2.setText("Corretor: ");

        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ganhos no Mês: ");

        jLabel4.setText("Ganhos no Ano: ");

        jTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/yyyy"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPagar)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonCancelar))
                    .addComponent(jComboBoxCorretor, 0, 251, Short.MAX_VALUE)
                    .addComponent(jTextFieldGanhoMes)
                    .addComponent(jTextFieldGanhoAno)
                    .addComponent(jTextFieldData))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonPagar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldGanhoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldGanhoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPagar)
                    .addComponent(jButtonCancelar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void iniciaArrays(Vector<Corretor> pCorretor) {
        vec = pCorretor;
        String[] str = new String[vec.size()];
        int cont = 0;
        for (Corretor ct : vec) {
            str[cont] = ct.getNome();
            cont++;
        }
        jComboBoxCorretor.setModel(new javax.swing.DefaultComboBoxModel<>(str));
    }

    //Caso seja precionado o botão de cancelar o programa irá deixar os campos vazios para a próxima execução, e fechará a janela
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldData.setText("");
        jTextFieldGanhoAno.setText("");
        jTextFieldGanhoMes.setText("");
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    //Caso seja precionado o botão pagar, o programa pegará a data e o corretor e calculará o salário dele
    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        double ganhoMes = 0, ganhoAno = 0;

        Corretor cor = vec.elementAt(jComboBoxCorretor.getSelectedIndex());
        //Separa a data recebida, para poder comparar seu mês e ano
        String str = jTextFieldData.getText();

        if (str.isEmpty()) {//Caso não seja digitado nada no campo pagamento
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Data Desejada no padrão (mm/yyyy) !", "Data Inválida", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] split = str.split("/");
        //Coloca os valores do mês e ano nas sequintes variáveis
        int mesEscolhido = Integer.parseInt(split[0]);
        int anoEscolhido = Integer.parseInt(split[1]);

        if (mesEscolhido < 1 || mesEscolhido > 12 || anoEscolhido < 2000 || anoEscolhido > 2018) {
            JOptionPane.showMessageDialog(rootPane, "Data Inválida", "Data Inválida", JOptionPane.ERROR_MESSAGE);
        } else {

            ganhoMes = ctrVenda.pagCorretorMes(mesEscolhido, anoEscolhido, cor);
            ganhoAno = ctrVenda.pagCorretorAnual(mesEscolhido, anoEscolhido, cor);

            //Mostra o valor do salário
            jTextFieldGanhoMes.setText("R$" + ganhoMes);
            jTextFieldGanhoAno.setText("R$" + ganhoAno);
        }

    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        jTextFieldData.setText("");
        jTextFieldGanhoAno.setText("");
        jTextFieldGanhoMes.setText("");
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JComboBox<String> jComboBoxCorretor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldGanhoAno;
    private javax.swing.JTextField jTextFieldGanhoMes;
    // End of variables declaration//GEN-END:variables
}
