/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package limit;

import control.*;
import java.util.Vector;
import javax.swing.*;
import model.*;

/**
 *
 * @author Kevin
 */
public class LimiteVendas extends javax.swing.JFrame {

    private ControleVendas ctrVendas;
    private Vector<Imovel> vecImovel;
    private Vector<Corretor> vec;

    public LimiteVendas(ControleVendas pCtrVendas) {
        ctrVendas = pCtrVendas;
        vecImovel = new Vector();
        vec = new Vector();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboCodImovel = new javax.swing.JComboBox<>();
        jLabelCodImovel = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jFormattedTextValor = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboCorretor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaImovel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Vector<Imovel> vecImovel = ctrVendas.getCtrPrincipal().getObjControleImovel().getVecImovel();
        String[] str = new String[vecImovel.size()];
        int cont = 0;
        for(Imovel im: vecImovel){
            str[cont] = im.getCodigo();
            cont++;
        }
        jComboCodImovel.setModel(new javax.swing.DefaultComboBoxModel<>(str));
        jComboCodImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCodImovelActionPerformed(evt);
            }
        });

        jLabelCodImovel.setText("Código de Imóvel: ");

        jLabelValor.setText("Valor da Venda: ");

        jFormattedTextValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel1.setText("R$");

        jLabel2.setText("Data da Venda: ");

        jFormattedTextData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel3.setText("Nome Comprador: ");

        jButtonConfirmar.setText("Confirmar Venda");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Corretor: ");

        Vector<Corretor> vec = ctrVendas.getCtrPrincipal().getObjControleCorretor().getVecCorretor();
        String[] str2 = new String[vec.size()];
        int cont2 = 0;
        for(Corretor ct: vec){
            str2[cont2] = ct.getNome();
            cont2++;
        }
        jComboCorretor.setModel(new javax.swing.DefaultComboBoxModel(str2));
        jComboCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCorretorActionPerformed(evt);
            }
        });

        jLabel5.setText("Informações do Imóvel");

        AreaImovel.setColumns(20);
        AreaImovel.setRows(5);
        jScrollPane2.setViewportView(AreaImovel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jComboCodImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelCodImovel)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValor)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jFormattedTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextValor)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboCodImovel, jComboCorretor, jFormattedTextData, jScrollPane2, jTextNome});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodImovel)
                        .addGap(7, 7, 7)
                        .addComponent(jComboCodImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelValor))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonConfirmar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void iniciaArrays(Vector<Imovel> pImovel, Vector<Corretor> pCorretor) {
        vecImovel = pImovel;
        vec = pCorretor;

        String[] str = new String[vecImovel.size()];
        int cont = 0;
        for (Imovel im : vecImovel) {
            str[cont] = im.getCodigo();
            cont++;
        }
        jComboCodImovel.setModel(new javax.swing.DefaultComboBoxModel<>(str));

        String[] str2 = new String[vec.size()];
        int cont2 = 0;
        for (Corretor ct : vec) {
            str2[cont2] = ct.getNome();
            cont2++;
        }
        jComboCorretor.setModel(new javax.swing.DefaultComboBoxModel(str2));

        Imovel i = vecImovel.get(jComboCodImovel.getSelectedIndex());
        AreaImovel.setText("Proprietário: " + i.getNomePropietario() + "\nPreço: R$" + i.getPreco()+ "\nTipo: "+ i.getTipo());

    }


    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        try {
            ctrVendas.cadVenda(jComboCodImovel.getSelectedIndex(),
                    jComboCorretor.getSelectedIndex(),
                    jTextNome.getText(),
                    jFormattedTextData.getText(),
                    jFormattedTextValor.getText()
            );

            JOptionPane.showMessageDialog(rootPane, "Venda cadastrado com sucesso",
                    "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar venda\n\n"
                    + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        //Após o cadastro deixará os campos vazios para um próximo cadastro 
        jTextNome.setText("");
        jFormattedTextData.setText("");
        jFormattedTextValor.setText("");
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    //Caso seja apertado o botão cancelar o programa fechará a janela de cadastro
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCorretorActionPerformed

    }//GEN-LAST:event_jComboCorretorActionPerformed

    private void jComboCodImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCodImovelActionPerformed
        Imovel i = vecImovel.get(jComboCodImovel.getSelectedIndex());
        AreaImovel.setText("Proprietário: " + i.getNomePropietario() + "\nPreço: R$" + i.getPreco()+ "\nTipo: "+ i.getTipo());
    }//GEN-LAST:event_jComboCodImovelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaImovel;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboCodImovel;
    private javax.swing.JComboBox<String> jComboCorretor;
    private javax.swing.JFormattedTextField jFormattedTextData;
    private javax.swing.JFormattedTextField jFormattedTextValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCodImovel;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
}
