/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package limit;

import util.*;

/**
 *
 * @author linux
 */
public class LimiteFormularios extends javax.swing.JFrame {

    /**
     * Creates new form LimiteFormularios
     */
    float valorM;
    String selectionForm = new String();

    public LimiteFormularios(float pValor, String selForm) {
        valorM = pValor;
        selectionForm = selForm;
        this.setVisible(true);
        initComponents();
        selecionaJanela(selForm);
    }

    public LimiteFormularios() {
        initComponents();
    }

    public void selecionaJanela(String selForm) {
        switch (selForm) {
            case Util.FATURAMENTO:
                jPanelCardLayout.removeAll();
                jPanelCardLayout.add(jPanelFaturamentoTotal);
                jPanelCardLayout.revalidate();
                jTextAreaFaturamentoTotal.setText("O lucro total da empresa foi de:" +
                        "\n " + "R$"
                        + valorM + ".");
            case Util.FUNCIONARIO_DO_MES:
            case Util.LUCRO:

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCardLayout = new javax.swing.JPanel();
        jPanelFaturamentoTotal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneTextoFaturamento = new javax.swing.JScrollPane();
        jTextAreaFaturamentoTotal = new javax.swing.JTextArea();
        jPanelLucroTotal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLucroTotal = new javax.swing.JTextArea();
        jPanelCorretorDoMes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPaneCorretorDoMes = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelCardLayout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCardLayout.setLayout(new java.awt.CardLayout());

        jPanelFaturamentoTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Faturamento total:");

        jTextAreaFaturamentoTotal.setColumns(20);
        jTextAreaFaturamentoTotal.setRows(5);
        jScrollPaneTextoFaturamento.setViewportView(jTextAreaFaturamentoTotal);

        javax.swing.GroupLayout jPanelFaturamentoTotalLayout = new javax.swing.GroupLayout(jPanelFaturamentoTotal);
        jPanelFaturamentoTotal.setLayout(jPanelFaturamentoTotalLayout);
        jPanelFaturamentoTotalLayout.setHorizontalGroup(
            jPanelFaturamentoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFaturamentoTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFaturamentoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPaneTextoFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFaturamentoTotalLayout.setVerticalGroup(
            jPanelFaturamentoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFaturamentoTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTextoFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanelCardLayout.add(jPanelFaturamentoTotal, "card2");

        jPanelLucroTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Lucro total:");

        jTextAreaLucroTotal.setColumns(20);
        jTextAreaLucroTotal.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLucroTotal);

        javax.swing.GroupLayout jPanelLucroTotalLayout = new javax.swing.GroupLayout(jPanelLucroTotal);
        jPanelLucroTotal.setLayout(jPanelLucroTotalLayout);
        jPanelLucroTotalLayout.setHorizontalGroup(
            jPanelLucroTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLucroTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLucroTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelLucroTotalLayout.setVerticalGroup(
            jPanelLucroTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLucroTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanelCardLayout.add(jPanelLucroTotal, "card3");

        jPanelCorretorDoMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Corretor do mês:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPaneCorretorDoMes.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanelCorretorDoMesLayout = new javax.swing.GroupLayout(jPanelCorretorDoMes);
        jPanelCorretorDoMes.setLayout(jPanelCorretorDoMesLayout);
        jPanelCorretorDoMesLayout.setHorizontalGroup(
            jPanelCorretorDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorretorDoMesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCorretorDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPaneCorretorDoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCorretorDoMesLayout.setVerticalGroup(
            jPanelCorretorDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorretorDoMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCorretorDoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanelCardLayout.add(jPanelCorretorDoMes, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LimiteFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LimiteFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LimiteFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LimiteFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LimiteFormularios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelCardLayout;
    private javax.swing.JPanel jPanelCorretorDoMes;
    private javax.swing.JPanel jPanelFaturamentoTotal;
    private javax.swing.JPanel jPanelLucroTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneCorretorDoMes;
    private javax.swing.JScrollPane jScrollPaneTextoFaturamento;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextAreaFaturamentoTotal;
    private javax.swing.JTextArea jTextAreaLucroTotal;
    // End of variables declaration//GEN-END:variables
}
