/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package limit;

import control.ControlePrincipal;
import javax.swing.table.DefaultTableModel;
import util.Util;

/**
 *
 * @author Rodrigo Maia
 */
public class MainWindow extends javax.swing.JFrame {

    private ControlePrincipal ctrPrincipal;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(ControlePrincipal pCtrPrincipal) {
        ctrPrincipal = pCtrPrincipal;
        initComponents();
        /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/

    }

    //Defini uma model para a tabela corretores
    public void setModelTableCorretores(DefaultTableModel pTableModel) {
        tableCorretores.removeAll();
        tableCorretores.setModel(pTableModel);
    }

    public void setModelTableImoveis(DefaultTableModel pTableModel){
        tableImoveis.removeAll();
        tableImoveis.setModel(pTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCorretores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableImoveis = new javax.swing.JTable();
        filtroImoveis = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jMenuBarMainWindow = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        menuItemComissionado = new javax.swing.JMenuItem();
        menuItemContratado = new javax.swing.JMenuItem();
        menuItemImovel = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuCadVenda = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tableCorretores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCorretores.setShowVerticalLines(false);
        tableCorretores.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tableCorretores);

        tableImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableImoveis);

        filtroImoveis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnExcluir.setText("Excluir");

        btnEditar.setText("Editar");

        jMenuCadastros.setText("Cadastrar");

        menuItemComissionado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemComissionado.setText("Comissionado");
        menuItemComissionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemComissionadoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemComissionado);

        menuItemContratado.setText("Contratado");
        menuItemContratado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContratadoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemContratado);

        menuItemImovel.setText("Imóvel");
        menuItemImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemImovelActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemImovel);

        jMenuBarMainWindow.add(jMenuCadastros);

        jMenuVendas.setText("Realizar vendas");

        jMenuCadVenda.setText("Cadastrar Vendas");
        jMenuCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadVendaActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuCadVenda);

        jMenuBarMainWindow.add(jMenuVendas);

        jMenuRelatorios.setText("Relatorios");

        jMenuItem4.setText("Faturamento Total");
        jMenuRelatorios.add(jMenuItem4);

        jMenuItem5.setText("Lucro Total");
        jMenuRelatorios.add(jMenuItem5);

        jMenuItem3.setText("Relação de Imóveis Vendidos");
        jMenuRelatorios.add(jMenuItem3);

        jMenuItem6.setText("Relação de Imóveis Encalhados ");
        jMenuRelatorios.add(jMenuItem6);

        jMenuItem7.setText("Faturamento de Cada Corretor");
        jMenuRelatorios.add(jMenuItem7);

        jMenuItem8.setText("Valor Pago a Cada Corretor");
        jMenuRelatorios.add(jMenuItem8);

        jMenuItem9.setText("Corretor do Mês");
        jMenuRelatorios.add(jMenuItem9);

        jMenuBarMainWindow.add(jMenuRelatorios);

        setJMenuBar(jMenuBarMainWindow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtroImoveis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filtroImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemComissionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemComissionadoActionPerformed

        ctrPrincipal.abrirJanelaCadastro(Util.CADASTRO_COMISSIONADO);
    }//GEN-LAST:event_menuItemComissionadoActionPerformed

    private void menuItemContratadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContratadoActionPerformed

        ctrPrincipal.abrirJanelaCadastro(Util.CADASTRO_CONTRATADO);
    }//GEN-LAST:event_menuItemContratadoActionPerformed

    private void menuItemImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemImovelActionPerformed

        ctrPrincipal.abrirJanelaCadastroImovel();

    }//GEN-LAST:event_menuItemImovelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        ctrPrincipal.finalize();

    }//GEN-LAST:event_formWindowClosing

    //Caso seja escolhido a opção de cadastro de vendas, o programa irá abrir a janela para que mesmo cadastre a venda
    private void jMenuCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadVendaActionPerformed
        ctrPrincipal.abrirJanelaCasdastroVenda();
    }//GEN-LAST:event_jMenuCadVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> filtroImoveis;
    private javax.swing.JMenuBar jMenuBarMainWindow;
    private javax.swing.JMenuItem jMenuCadVenda;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuItemComissionado;
    private javax.swing.JMenuItem menuItemContratado;
    private javax.swing.JMenuItem menuItemImovel;
    private javax.swing.JTable tableCorretores;
    private javax.swing.JTable tableImoveis;
    // End of variables declaration//GEN-END:variables
}
